name: Publish
on:
  push:
    branches:
      - 'next'
  workflow_dispatch:

  workflow_call:
    
concurrency:
  group: package-publishing

jobs:
  publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - run: git pull

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build, Version & Publish packages
        run: yarn run publish
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
          npm_config_registry: 'https://registry.npmjs.org'
