name: Publish
on:
  push:
    branches:
      - 'next'
  workflow_dispatch:

  workflow_call:
    
concurrency:
  group: package-publishing

jobs:
  publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - run: git pull

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build, Version & Publish packages
        run: yarn run publish
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
          NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org'
